export default () => ({
	"after":"2",
	"ref":"",
	"before":"1",
	"compare":"",
	"forced":false,
	"created":false,
	"deleted":false,
	"project":{
		"uuid":"f1115b9c-b165-46de-85a7-251805537746",
		"name":"demo-",
		"url":"https://app.deveo.com/Gexample/projects/demo-"
	},
	"repository":{
		"uuid":"19cf0c6f-0743-4e4f-9e28-17f504476c34",
		"name":"svn1",
		"type":"subversion",
		"url":"https://app.deveo.com/Gexample/projects/demo-/repositories/svn1",
		"https_url":"https://app.deveo.com/Gexample/projects/demo-/repositories/subversion/svn1",
		"ssh_url":"svn+ssh://deveo@app.deveo.com/Gexample/projects/demo-/repositories/subversion/svn1",
		"owner":{
			"uuid":"537cf937-427d-4b4a-9133-0dba0341262a",
			"name":"doejohn",
			"email":"ilmari@deveo.com"
		}
	},
	"pusher":{
		"uuid":"537cf937-427d-4b4a-9133-0dba0341262a",
		"name":"doejohn",
		"display_name":"John Doe"
	},
	"commit_count":1,
	"commits":[
		{
			"distinct":true,
			"removed":[],
			"message":"More text for DeveoSVN.",
			"added":[],
			"timestamp":"2016-09-07T15:05:20Z",
			"modified":["README.md"],
			"url":"https://app.deveo.com/Gexample/projects/demo-/repositories/svn1/changesets/2",
			"author":{
				"name":"doejohn",
				"email":""
			},
			"id":"2"
		}
	]
});